### ISSUE TITLE
Issue on page /stat/hazard_models.html

### ISSUE THREAD

**Issue by Dont-Care-Didnt-Ask** [ComputationalAgingLab/computational_aging_course#11]
> 3.1 Survival curve
Let $T$ is a non-negative random variable with a corresponding distribution function:
$F(t) = P(T < t)$
We call $T$ survival time or time before death of some object (e.g. human). For example, 
 can have normal distribution:

Strictly speaking, normal distribution is defined over all real numbers, so it would be better to illustrate the concept, using exponential or Weibull distribution (the last already occured in the course, so it seems fitting, the former might be an easier example).

If you keep the normal distribution, at least make a note that actually normal is not non-negative, but for certain parameters (say mean lifespan of 70 years and standard deviation of 15 years) the probability of getting a negative value is extremely low and could be ignored in practice.

**Comment by shappiron** [comment]
It will be fixed in the next commit. Thank you!
